services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - ../apps/backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  backend:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.backend
    ports:
      - "4000:4000"
    env_file:
      - ../apps/backend/.env
    environment:
      - NODE_ENV=production
    depends_on:
      - db
      - redis
    networks:
      - mynetwork

  frontend:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.frontend
    ports:
      - "80:3000"
    env_file:
      - ../apps/site/.env
    environment:
      - NODE_ENV=production
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork: