services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - ../apps/backend/.env
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

volumes:
  postgres_data_dev:
