FROM node:22 as builder

WORKDIR /usr/src/site

COPY ../pnpm-lock.yaml ../package.json ./

RUN corepack enable && corepack prepare pnpm@9.4.0 --activate

RUN pnpm install --frozen-lockfile

RUN pnpm turbo prune --scope=frontend

COPY . .

RUN pnpm install --frozen-lockfile

RUN pnpm build

FROM nginx:stable

COPY --from=builder /usr/src/site/dist /usr/share/nginx/html

EXPOSE 80
